### ISSUE TITLE
3 Punches/3 Kicks hotkeys not available

### ISSUE THREAD

**Issue by pokeshark** [libretro/FBNeo#194] opened 2019-11-11 20:20 UTC
Any plans to port from the standalone version the hotkeys (3 Punches/3 Kicks/AB/CD etc.) for remapping from Quick Menu - Controls?

**Comment by barbudreadmon** [comment] 2019-11-11 20:45
duplicate of https://github.com/libretro/FBNeo/issues/51, closing

**Closed by barbudreadmon** 2019-11-11 20:45 UTC

**Comment by pokeshark** [comment] 2019-11-11 22:24
oops. sorry, didn't see it.
