### ISSUE TITLE
[iOS] & [macOS] Commit breaks standard compilation from libretro-super

### ISSUE THREAD

**Issue by WeedyWeedSmoker** [libretro/FBNeo#980] opened 2022-04-15 04:18 UTC
Commit 3dc220053c680e172aa9891411b7123e65336c5d broke compilation for iOS and macOS for standard libretro-super compilation

Latest commit still spits out errors like those:
```
../../burner/libretro/libretro.cpp:372:19: error: non-const lvalue reference to type 'basic_ostringstream<...>' cannot bind to a temporary of type 'basic_ostringstream<...>'
                                option_name = SSTR( "DIPSWITCH " << dipswitch_core_options.size() );
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/retro_common.h:10:19: note: expanded from macro 'SSTR'
#define SSTR( x ) static_cast< std::ostringstream & >(( std::ostringstream() << std::dec << x ) ).str()
                  ^                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/libretro.cpp:376:32: error: non-const lvalue reference to type 'basic_ostringstream<...>' cannot bind to a temporary of type 'basic_ostringstream<...>'
                        dip_option->friendly_name = SSTR( "[Dipswitch] " << option_name.c_str() );
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/retro_common.h:10:19: note: expanded from macro 'SSTR'
#define SSTR( x ) static_cast< std::ostringstream & >(( std::ostringstream() << std::dec << x ) ).str()
                  ^                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/libretro.cpp:383:30: error: non-const lvalue reference to type 'basic_ostringstream<...>' cannot bind to a temporary of type 'basic_ostringstream<...>'
                        dip_option->option_name = SSTR( "fbneo-dipswitch-" << drvname << "-" << option_name.c_str() );
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/retro_common.h:10:19: note: expanded from macro 'SSTR'
#define SSTR( x ) static_cast< std::ostringstream & >(( std::ostringstream() << std::dec << x ) ).str()
                  ^                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/libretro.cpp:391:32: error: non-const lvalue reference to type 'basic_ostringstream<...>' cannot bind to a temporary of type 'basic_ostringstream<...>'
                                        dip_option->option_name = SSTR( "fbneo-dipswitch-" << drvname << "-" << option_name.c_str() << "_" << dup_nbr );
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/retro_common.h:10:19: note: expanded from macro 'SSTR'
#define SSTR( x ) static_cast< std::ostringstream & >(( std::ostringstream() << std::dec << x ) ).str()
                  ^                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/libretro.cpp:562:34: error: non-const lvalue reference to type 'basic_ostringstream<...>' cannot bind to a temporary of type 'basic_ostringstream<...>'
                        cheat_option->friendly_name = SSTR( "[Cheat] " << option_name.c_str() );
                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/retro_common.h:10:19: note: expanded from macro 'SSTR'
#define SSTR( x ) static_cast< std::ostringstream & >(( std::ostringstream() << std::dec << x ) ).str()
                  ^                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/libretro.cpp:567:32: error: non-const lvalue reference to type 'basic_ostringstream<...>' cannot bind to a temporary of type 'basic_ostringstream<...>'
                        cheat_option->option_name = SSTR( "fbneo-cheat-" << num << "-" << drvname << "-" << option_name.c_str() );
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/retro_common.h:10:19: note: expanded from macro 'SSTR'
#define SSTR( x ) static_cast< std::ostringstream & >(( std::ostringstream() << std::dec << x ) ).str()
                  ^                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/libretro.cpp:577:34: error: non-const lvalue reference to type 'basic_ostringstream<...>' cannot bind to a temporary of type 'basic_ostringstream<...>'
                                cheat_value->friendly_name = SSTR( i << " - " << option_value_name.c_str());
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/retro_common.h:10:19: note: expanded from macro 'SSTR'
#define SSTR( x ) static_cast< std::ostringstream & >(( std::ostringstream() << std::dec << x ) ).str()
                  ^                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/libretro.cpp:578:69: error: non-const lvalue reference to type 'basic_ostringstream<...>' cannot bind to a temporary of type 'basic_ostringstream<...>'
                                if (pCurrentCheat->nDefault == i) cheat_option->default_value = SSTR( i << " - " << option_value_name.c_str());
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burner/libretro/retro_common.h:10:19: note: expanded from macro 'SSTR'
#define SSTR( x ) static_cast< std::ostringstream & >(( std::ostringstream() << std::dec << x ) ).str()
                  ^                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 8 errors generated.
```

Buildbot still compiles for those platforms, so it might be fixed by adding the necessary changes for libretro-super, or in makefiles?

@barbudreadmon 
@twinaphex

**Comment by barbudreadmon** [comment] 2022-04-15 04:58
Makefiles are fine or the buildbot would be unable to build, so this isn't an issue with this repo.

**Comment by WeedyWeedSmoker** [comment] 2022-04-15 06:54
@barbudreadmon Might be c++ arguments that should be added somewhere for the standard recipe? (Sorry for the probably not very helpful non-coder insight…)

**Comment by barbudreadmon** [comment] 2022-04-15 09:15
Don't ask me, i know nothing about the libretro-super recipes, you should ask there. All i can tell is that the buildbot builds the core successfully using my makefile, so my makefile is fine.

**Comment by WeedyWeedSmoker** [comment] 2022-04-15 09:33
Any bright insight as to why this happens @twinaphex ?

**Comment by barbudreadmon** [comment] 2022-04-15 09:45
Does it build if you replace https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/retro_common.h#L10 by
```
#define SSTR( x ) static_cast< const std::ostringstream & >(( std::ostringstream() << std::dec << x ) ).str()
```
?

https://stackoverflow.com/questions/63186574/why-does-this-code-give-the-error-cannot-bind-non-const-lvalue-reference-of-typ seems to tell this error might be happening because the compiler expects a `const`, no idea why it would only happen with your compiler though.

**Comment by WeedyWeedSmoker** [comment] 2022-04-15 10:39
Yes! That fixed it!

Compiles fine now, I'm using the latest macOS version with the latest Xcode and command-line tools, on a Hackintosh but that should not affect anything aside from the price of my machine… ;D

Thanks @barbudreadmon !

**Comment by barbudreadmon** [comment] 2022-04-15 12:01
Hmmm ok, i commited that fix since it doesn't seem to cause any regression, closing.

**Closed by barbudreadmon** 2022-04-15 12:01 UTC
