### ISSUE TITLE
Atari Gauntlet (gauntlet). Cannot play any level beyond level 1

### ISSUE THREAD

**Issue by roslof** [libretro/FBNeo#392] opened 2020-07-11 16:32 UTC
**Summary:**
There are three (3) Exits in Level 1. Using any exit (to Level 2, To Level 4 or to Level 8) results in impossible game boards.

**FinalBurn Neo Version Tested***
v0.2.94.44 (commit 706d8ae)
*Note: tested version does not suggest issue was introduced with this version.

**Current Behavior**
When taking the **Level 2** Exit, player will be placed in between solid walls with no way out, no timer to remove walls and a voice over "try to find a way out". Play cannot advance.

When taking the **Level 4 Exit**, world will scroll and player is not visible. Play cannot advance.

When taking the **Level 8 Exit**, player is placed into a corrupt world. Navigating will eventually result in a freeze.

**Expected Behavior**
(Reference MAME 0.220 for correct behavior)
Levels 2, 4 and 8 should load properly.

**Comment by barbudreadmon** [comment] 2020-07-12 08:15
I can't seem to reproduce this, are you using some non-default setting ?

**Comment by barbudreadmon** [comment] 2020-07-12 10:00
I believe the issue is related to the use of `char` instead `INT8` "somewhere", i'll try to find the culprit

**Comment by barbudreadmon** [comment] 2020-07-12 14:25
Fixed by https://github.com/libretro/FBNeo/commit/6102728d2246d14f596ddf97c8b7da9deeb7aad0 , special thanks to @dinkc64 who figured out the problem 1 minute after i mentioned it

**Closed by barbudreadmon** 2020-07-12 14:25 UTC

**Comment by roslof** [comment] 2020-07-12 18:10
Amazing team you guys have. I'll specify device in future reports to avoid confusion. I expect to exclusively be testing on Raspberry Pi 4B, but will make note.
