### ISSUE TITLE
Mad Planets (mplanets) - High score table entry cursor is misaligned.

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#432] opened 2020-07-30 05:50 UTC
**Summary:**
Box for selecting letters for initial entry to high-score table is misaligned.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 282f38f)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 f17b938)

**Steps:**
Achieve a score that will place you on the high-score table (very easy) and try to enter your initials.

**Results:**
![mplanets-200730-064346](https://user-images.githubusercontent.com/13021896/88885659-d01c4c00-d230-11ea-9b8b-740c3ffd52af.png)
![mplanets-200730-064404](https://user-images.githubusercontent.com/13021896/88885661-d0b4e280-d230-11ea-86e1-026adcd7e83f.png)

The screenshots show the blue letter selection box at its top-left and bottom-right extents. It should be aligned to the letter A and the right arrow respectively, but it's offset to the upper right of where it should be. The blue box above is where the letters appear as you select them - it is also offset.

**Expected Results:**
Box should be aligned to the grid of letters. See MAME 0.222 for correct behaviour.

N.B. hope you're not mad about me reporting this _very_ minor issue!

**Comment by barbudreadmon** [comment] 2020-07-30 06:31
> hope you're not mad about me reporting this very minor issue!

We are never mad when someone reports an issue, anything that leads to better code is good, thanks for the report !

**Comment by dinkc64** [comment] 2020-07-30 12:57
Thank you, the problem is fixed now.
p.s. reports like this are always really nice!  :)

**Comment by adelpha** [comment] 2020-08-01 08:20
Confirmed fixed! Thanks!

**Closed** 2020-08-01 08:32 UTC
