### ISSUE TITLE
[Switch] Game-specific options not showing for certain games.

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [libretro/FBNeo#97] opened 2019-07-10 19:20 UTC
I looked in the cfg file and the game_specific_options were flipped to "true". I have the MK arcade games and options like turning the blood on and off were there.

However, I also have the Marvel Vs. Capcom games (X-Men vs. SF, MSH vs. SF, and M vs. C) and there should be options for assigning 3x punch and 3x kick to certain buttons (I know because I tried this on the Wii U version of FBN and they showed up) however the options do not show on the Switch version.  How is it that MK shows their game specific options but MVC doesn't??? Please help!

**Comment by barbudreadmon** [comment] 2019-07-10 20:29
duplicate of https://github.com/libretro/FBNeo/issues/51

**Closed by barbudreadmon** 2019-07-10 20:29 UTC
