### ISSUE TITLE
Feature Request: re-implement the 3P and 3K macros for CPS2 fighting games

### ISSUE THREAD

**Issue by prataczak** [libretro/FBNeo#509] opened 2020-08-19 11:49 UTC
I resisted switching to the new FBNeo core for the longest time, but I finally updated, and this was the first thing I noticed that was missing.

Standalone Final Burn Neo allows you to map 3 Punch and 3 Kick macros to the triggers (or any other button really), and the Final Burn Alpha core had this implemented as well, here's a screen shot:

![2020-08-19 (4)](https://user-images.githubusercontent.com/12243933/90631126-2e18cf80-e1f0-11ea-8156-fb8fe7b24119.png)

This may not seem like a big deal to some, but many users of the standalone app, as well as users of 'Fightcade' have become accustomed to having these special macros, as they make games like Marvel vs. Capcom much easier to play, with easier super moves, dashes, and super jumps.

Please consider re-implementing this feature. Thanks for your consideration.

**Comment by barbudreadmon** [comment] 2020-08-19 12:34
duplicate of https://github.com/libretro/FBNeo/issues/51, the answer didn't change

**Comment by prataczak** [comment] 2020-08-19 13:01
No disrespect intended, but after reading the other thread, I still don't understand why it was removed. I'm going to speak frankly and hopefully it doesn't come off as me being an ass, because I respect what you and others contribute immensely.

"My main issue with the implementation on core's side is that it's causing issues with netplay if options are different between clients, having it on frontend's side would prevent this issue. I know it's an important feature, that's why i think its implementation in RA should be made a priority, so that all cores can benefit from it."

This seems like a non issue to me. If I want to play retro fighting games with other people online, no disrespect intended to anyone involved with RetroArch, but I (and most people) are going to use FightCade, because the netplay experience it offers is far superior. But, if I DID want to use RetroArch, it's not a big deal at all to make sure settings are the same on both ends if need be, and it's feasible that any number of the other settings would be different anyways. I get that it's better to have it on the frontend's side, but the netplay issue alone doesn't seem like a good enough reason to justify nixing it, when so many people use it and benefit from it.

It's your project and you're free to do as you please, but you took away something people enjoyed using, and that kinda sucks.  Users now have a choice to wait an eternity for what you proposed to actually happen (18 months and counting), use the standalone, or continue to use the Final Burn Alpha core, if they're lucky enough to still have it, which I may very well do.

**Closed** 2020-08-19 13:03 UTC

**Comment by barbudreadmon** [comment] 2020-08-19 14:06
You are mixing your personal beliefs with reality : 
- i don't see why fightcade would be better than retroarch for netplay, it's probably the other way around with retroarch supporting negative input latency on netplay for a long time
- i'm not gonna argue about the usefulness of those macros, i can understand why some people prefer "easymode", but 3-4 people complaining about it over the course of 2 years doesn't make "many people".

Furthermore, you make it look as if i took it out for fun but that's not the case : the feature was broken (NB: the first time it was reported was at least 6 months after it broke), i didn't know how to fix it and wasn't interested with libretro's policy of not having input related thingies in core options, and later i learnt the code was actually preventing the core to build for some platforms. Anyway, feel free to use whatever you want to play those games.

**Comment by prataczak** [comment] 2020-08-19 14:25
Perception IS reality. :) If you see a 6 and I see a 9, maybe I'm right, maybe you're right, maybe we're both right, or maybe we're both wrong it was supposed to be a G. But at the end of the day it's just a point of view, and objective truth is for fools and fanatics.

Anyways Fightcade uses GGPO code, which may or may not be equal to RetroArch's runahead (I think it's actually very similar), but the fact that you can replay any match at a later date, a ranking system, a much more intuitive and useful online experience, and a much larger user database makes it far superior IN MY OPINION. :)

Like most things, 3-4 people complain about it, and the other 50 decide that it's way too much effort to try to rock the status quo and just adapt. I can assure you, FBNeo, and FBA far longer than that is well loved because of this feature.

The explanation you just gave makes sense, sorry for making you seem like you were being petty, when I clearly didn't have all of the facts.

**Comment by dinkc64** [comment] 2020-09-04 13:05
I think the macros should be added back, too :)  I don't use retroarch though, but those macros are one thing that players love about fbneo.

**Comment by barbudreadmon** [comment] 2020-09-04 15:21
i was talking about this with a retroarch dev just yesterday, there might be some progress through https://github.com/libretro/RetroArch/issues/11273

**Comment by barbudreadmon** [comment] 2021-04-22 09:55
3xPunch & 3xKick macros were re-implemented, just those 2 for now since the libretro limitation about the number of different inputs/actions is still there
