### ISSUE TITLE
Autofire

### ISSUE THREAD

**Issue by Chandler-Kluser** [libretro/FBNeo#355] opened 2020-06-07 01:59 UTC
Hello everybody,

I can run neo geo roms without any major issues on my PC's. But something is getting me mad when I play games like aero fighters/sonic wings: **the autofire option**.

I've run on my two PC's with retroarch in Manjaro Linux. Althought there is an autofire option in the content menu, there is no effect by enabling It...

Can someone explain me if this is an issue of my PC's or if the emulator does not have this option by itself.

Thanks in advance, you are doing a great job!

**Comment by barbudreadmon** [comment] 2020-06-07 07:16
Long story short : the dipswitch is closely tied to a frontend feature RetroArch doesn't offer. This issue is basically a duplicate of https://github.com/libretro/FBNeo/issues/51, macro & autofire buttons need an implementation frontend side.

**Closed by barbudreadmon** 2020-06-07 07:16 UTC
