### ISSUE TITLE
Select button not working on some neogeo games

### ISSUE THREAD

**Issue by Sakitoshi** [libretro/FBNeo#86] opened 2019-07-03 03:42 UTC
Not the coin button, but the select button that replaces it in the neogeo aes (home console).
the affected games (that I know of, maybe there are more) are the last blade 1 and 2 and matrimelee.
in the last blade 1 and 2 the select button should bring up a menu while in training mode and pause the game during normal gameplay, but right now it does nothing.
matrimelee lacks a training mode, but it should pause the game during a fight.

I'm using the unibios 3.2 if that makes a difference.

**Comment by thomasgoldstein** [comment] 2019-07-03 05:37
This must be the cause: https://neo-source.com/index.php?topic=3490.msg27251#msg27251

**Comment by barbudreadmon** [comment] 2019-07-03 05:58
While i don't care at all about pausing gameplay, i didn't know about the last blade training menu.
Mapping neogeo select to select button is not gonna happen anymore for the reasons explained in the forum, but i can map it to a free button, let's say L3 then...

**Comment by barbudreadmon** [comment] 2019-07-03 06:04
Done : https://github.com/libretro/FBNeo/commit/666d7f04f9018c4e9a5f1c216d49c81ae9e0dd08
Closing

**Closed by barbudreadmon** 2019-07-03 06:04 UTC
