### ISSUE TITLE
Poker Ladies (pkladies): Player cannot choose cards to "Hold".

### ISSUE THREAD

**Issue by roslof** [libretro/FBNeo#394] opened 2020-07-12 02:07 UTC
Poker Ladies is a typical "Jacks or Better" Video Poker game.
Once 5 cards are dealt, the player is intended to choose cards to Hold. When done, they draw the substitute cards.

**Issue:**
Currently, it doesn't appear there are controls to support Hold.

**Expected Results**
Player should be able to "Hold" any combination of the dealt cards.

**Reference**
lr-mame (0.220) uses keyboard keys Z,X,C,V and B to toggle card hold.

**Comment by barbudreadmon** [comment] 2020-07-12 08:30
That one would be a duplicate of https://github.com/libretro/FBNeo/issues/71

**Closed** 2020-09-12 06:25 UTC
