### ISSUE TITLE
wrally2 - Retroarch menu glitch

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/FBNeo#18] opened 2019-05-22 07:48 UTC
When running wrally2, if you try to open the menu it only shows blocks in the text, at least on the Ozone menu driver.

**Comment by barbudreadmon** [comment] 2019-05-22 08:22
It definitely looks like a weird RA bug to me : i can reproduce (with ozone) but the issue disappear when i toggle fullscreen/windowed. I also have an issue with controls until i toggle fullscreen/windowed (whatever the menu driver).
It might be related to the unusual aspect ratio ?

**Comment by Tatsuya79** [comment] 2019-05-22 14:59
```
[INFO] [SDL_GL] SDL 2.0.8 gfx context driver initialized.
[INFO] [GLCore]: Found GL context: sdl_gl
```
instead of
```
[INFO] [GLCore]: Found GL context: wgl
```
previously (older FBA core), also happens with Backfire.
Got an empty RA window + a 2nd window on top with the game on win7 x64, XMB menu driver, glcore.

**Comment by barbudreadmon** [comment] 2019-05-22 18:22
Fixed in https://github.com/libretro/FBNeo/commit/4dcb8ae73fa168b7a5fed488912072d19006410f

**Closed by barbudreadmon** 2019-05-22 18:22 UTC
