### ISSUE TITLE
Ludo crashes when loading a second game

### ISSUE THREAD

**Issue by kivutar** [libretro/FBNeo#165] opened 2019-10-01 13:53 UTC
During the `unload` callback, I'm getting a SIGABRT and an error message about a pointer freed that was not allocated.

Commenting these two calls fixed it:

```
diff --git a/src/burner/libretro/libretro.cpp b/src/burner/libretro/libretro.cpp
index 7d48f9f0..98bc4e34 100644
--- a/src/burner/libretro/libretro.cpp
+++ b/src/burner/libretro/libretro.cpp
@@ -1382,10 +1382,10 @@ void retro_unload_game(void)
        {
                if (BurnStateSave(g_autofs_path, 0) == 0 && path_is_valid(g_autofs_path))
                        log_cb(RETRO_LOG_INFO, "[FBNEO] EEPROM succesfully saved to %s\n", g_autofs_path);
-               if (pVidImage)
-                       free(pVidImage);
-               if (g_audio_buf)
-                       free(g_audio_buf);
+               //if (pVidImage)
+               //      free(pVidImage);
+               //if (g_audio_buf)
+               //      free(g_audio_buf);
                BurnDrvExit();
                if (nGameType == RETRO_GAME_TYPE_NEOCD)
                        CDEmuExit();
```

**Comment by barbudreadmon** [comment] 2019-10-01 15:45
It doesn't make any sense, those pointers are allocated in retro_load_game so they have to be freed in its mirror call `retro_unload_game`, furthermore i test they aren't null before freeing them.
Imho this issue is not core related and this ugly fix is not needed.

**Comment by kivutar** [comment] 2019-10-02 02:49
OK I'll investigate more. It's possible that the cause is Ludo.
However FBNeo is the only core that present this issue.

The code we use to unload the game is straightforward:

 1. https://github.com/libretro/ludo/blob/master/core/core.go#L192-L201
 2. https://github.com/libretro/ludo/blob/master/libretro/libretro.go#L420-L423

There is not much place for errors.

**Comment by barbudreadmon** [comment] 2019-10-02 03:51
I can't reproduce your issue at all with RetroArch, i checked my code again and everything seems sane.

**Comment by barbudreadmon** [comment] 2019-10-02 11:12
Fixed with https://github.com/libretro/FBNeo/commit/48ff5b58608f6229cf08516cf1c190159aa87896
Not sure which part of it though...

**Closed by barbudreadmon** 2019-10-02 11:12 UTC
