### ISSUE TITLE
Tough Turf (set 1, US, 8751 317-0099) (tturfu) locks up

### ISSUE THREAD

**Issue by Wilstorm** [libretro/FBNeo#170] opened 2019-10-04 18:57 UTC
Are you seeing any issues with Tough Turf (set 1, US, 8751 317-0099) (ROM name tturfu). When running the latest version of FBNeo on a Pi the game locks up. The game loads fine, I am able to insert quarters, and start the game. Which works perfectly. 

But after the game intro starts, the diesel backups and the rear doors open the game locks up. It's basically where the players jump out of the truck.

I tested tturf (Japan version) and it seems to work fine.

**Comment by barbudreadmon** [comment] 2019-10-05 06:03
No lock up here using the latest version **built from sources on my rpi3**. I fixed a bug with m68k a few days ago, so make sure you are building FBNeo from sources since this game is using m68k.

Otherwise make sure you aren't using core options that can cause various issues : 
- CPU clock above 100%
- Enabling cyclone

Closing

**Comment by Wilstorm** [comment] 2019-10-07 00:17
Do you have any other suggestions I might try? Here's more detailed information if it helps. I am running RetroPie 4.5.1 (896b34e1), FBNeo commit f92dd20 and Retroarch 1.7.6. 

I verified I am not using a CPU clock above 100% nor cyclone. I basically leave all settings at the default for FBNeo. 

I also disabled overclocking and removed any shaders, backdrops, etc. while testing. It's as plain as I can get it. 

The strange thing to me is tturf works flawless for 1 or 2 players but tturfu doesn't. It locks up completely at the intro screen right after it prints 300 in the upper right corner for the time and then the attract mode loop starts. I have to use PuTTY to reboot as you can't exit the game. It checked for the tturfu.fs file to delete it but it doesn't ever get created.

Below is my core settings from ```retroarch-core-options.cfg``` and the verbose launch log.

```
fba-aspect = "DAR"
fba-cpu-speed-adjust = "100"
fba-diagnostic-input = "None"
fba-dipswitch-pspikes2-Autofire = "(Default) Off"
fba-dipswitch-pspikes2-BIOS = "(Default) MVS Asia/Europe ver. 6 (1 slot)"
fba-dipswitch-pspikes2-Coin_chutes = "(Default) 1"
fba-dipswitch-pspikes2-Coin_chutes_2 = "(Default) 2"
fba-dipswitch-pspikes2-Commmunicaton = "(Default) Disabled"
fba-dipswitch-pspikes2-Free_play = "(Default) Off"
fba-dipswitch-pspikes2-Memory_card = "(Default) Writable"
fba-dipswitch-pspikes2-New_card_type = "(Default) Normal"
fba-dipswitch-pspikes2-Setting_mode = "(Default) Off"
fba-dipswitch-pspikes2-Stop_mode = "(Default) Off"
fba-dipswitch-pspikesu-1_Player_Starting_Score = "(Default) 12-12"
fba-dipswitch-pspikesu-2_Players_Starting_Score = "(Default) 9-9"
fba-dipswitch-pspikesu-2_Players_Time_Per_Credit = "(Default) 3 min"
fba-dipswitch-pspikesu-Coin_A = "(Default) 1 Coin  1 Credits"
fba-dipswitch-pspikesu-Coin_B = "(Default) 1 Coin  1 Credits"
fba-dipswitch-pspikesu-Debug = "(Default) Off"
fba-dipswitch-pspikesu-Demo_Sounds = "(Default) On"
fba-dipswitch-pspikesu-Difficulty = "(Default) Normal"
fba-dipswitch-pspikesu-Service_Mode = "(Default) Off"
fba-fm-interpolation = "4-point 3rd order"
fba-hiscores = "enabled"
fba-macro-pspikes2-P1_Buttons_AB = "None"
fba-macro-pspikes2-P1_Buttons_ABC = "None"
fba-macro-pspikes2-P1_Buttons_ABCD = "None"
fba-macro-pspikes2-P1_Buttons_ABD = "None"
fba-macro-pspikes2-P1_Buttons_AC = "None"
fba-macro-pspikes2-P1_Buttons_ACD = "None"
fba-macro-pspikes2-P1_Buttons_AD = "None"
fba-macro-pspikes2-P1_Buttons_BC = "None"
fba-macro-pspikes2-P1_Buttons_BCD = "None"
fba-macro-pspikes2-P1_Buttons_BD = "None"
fba-macro-pspikes2-P1_Buttons_CD = "None"
fba-macro-pspikes2-P2_Buttons_AB = "None"
fba-macro-pspikes2-P2_Buttons_ABC = "None"
fba-macro-pspikes2-P2_Buttons_ABCD = "None"
fba-macro-pspikes2-P2_Buttons_ABD = "None"
fba-macro-pspikes2-P2_Buttons_AC = "None"
fba-macro-pspikes2-P2_Buttons_ACD = "None"
fba-macro-pspikes2-P2_Buttons_AD = "None"
fba-macro-pspikes2-P2_Buttons_BC = "None"
fba-macro-pspikes2-P2_Buttons_BCD = "None"
fba-macro-pspikes2-P2_Buttons_BD = "None"
fba-macro-pspikes2-P2_Buttons_CD = "None"
fba-neogeo-mode = "MVS"
fba-sample-interpolation = "4-point 3rd order"
fba-samplerate = "48000"
fbneo-allow-depth-32 = "enabled"
fbneo-analog-speed = "100%"
fbneo-cpu-speed-adjust = "100%"
fbneo-cyclone = "disabled"
fbneo-diagnostic-input = "Hold Start"
fbneo-dipswitch-dkong-Bonus_Life = "7000"
fbneo-dipswitch-dkong-Cabinet = "Upright"
fbneo-dipswitch-dkong-Coinage = "1 Coin  1 Credits"
fbneo-dipswitch-dkong-Lives = "3"
fbneo-dipswitch-kov-Bios_select_(Fake) = "Newer"
fbneo-dipswitch-kov-Free_play = "Off"
fbneo-dipswitch-kov-Music = "On"
fbneo-dipswitch-kov-Region_(Fake) = "World"
fbneo-dipswitch-kov-Stop_mode = "Off"
fbneo-dipswitch-kov-Test_mode = "Off"
fbneo-dipswitch-kov-Voice = "On"
fbneo-dipswitch-mslug-Autofire = "Off"
fbneo-dipswitch-mslug-BIOS = "MVS Asia/Europe ver. 6 (1 slot)"
fbneo-dipswitch-mslug-Coin_chutes = "1"
fbneo-dipswitch-mslug-Coin_chutes_2 = "2"
fbneo-dipswitch-mslug-Commmunicaton = "Disabled"
fbneo-dipswitch-mslug-Free_play = "Off"
fbneo-dipswitch-mslug-Memory_card = "Writable"
fbneo-dipswitch-mslug-New_card_type = "Normal"
fbneo-dipswitch-mslug-Setting_mode = "Off"
fbneo-dipswitch-mslug-Stop_mode = "Off"
fbneo-dipswitch-touchgo-Coin_A = "1 Coin  1 Credits"
fbneo-dipswitch-touchgo-Coin_B = "1 Coin  1 Credits"
fbneo-dipswitch-touchgo-Coin_Slot = "Independent"
fbneo-dipswitch-touchgo-Credit_configuration = "1 Credit Start/1 Credit Continue"
fbneo-dipswitch-touchgo-Demo_Sounds = "On"
fbneo-dipswitch-touchgo-Difficulty = "Normal"
fbneo-dipswitch-touchgo-Monitor_Type = "Single monitor, 2 players"
fbneo-dipswitch-touchgo-Service_Mode = "Off"
fbneo-dipswitch-tturf-Bonus_Energy = "2"
fbneo-dipswitch-tturf-Coin_A = "1 Coin  1 Credit"
fbneo-dipswitch-tturf-Coin_B = "1 Coin  1 Credit"
fbneo-dipswitch-tturf-Continues = "None"
fbneo-dipswitch-tturf-Demo_Sounds = "On"
fbneo-dipswitch-tturf-Difficulty = "Normal"
fbneo-dipswitch-tturf-Starting_Energy = "6"
fbneo-fm-interpolation = "4-point 3rd order"
fbneo-frameskip = "0"
fbneo-hiscores = "enabled"
fbneo-load-subsystem-from-parent = "enabled"
fbneo-neogeo-mode = "DIPSWITCH"
fbneo-sample-interpolation = "4-point 3rd order"
fbneo-samplerate = "48000"
fbneo-vertical-mode = "disabled"
```
```
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-fbneo/fbneo_libretro.so --config 

/opt/retropie/configs/fba/retroarch.cfg "/home/pi/RetroPie/roms/fba/tturfu.zip" --verbose --appendconfig /dev/shm/retroarch.cfg
[INFO] RetroArch 1.7.6 (Git 9750719)
[INFO] 

Redirecting save file to "/home/pi/RetroPie/roms/fba/tturfu.srm".
[INFO] Redirecting savestate to "/home/pi/RetroPie/roms/fba/tturfu.state".
[INFO] === Build 

=======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Oct  1 2019
[INFO] Version: 1.7.6
[INFO] Git: 9750719
[INFO] 

=================================================
[INFO] Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-fbneo/fbneo_libretro.so"
[INFO] [overrides] no 

core-specific overrides found at /home/pi/.config/retroarch/config/FinalBurn Neo/FinalBurn Neo.cfg.
[INFO] [overrides] no content-dir-specific overrides found at 

/home/pi/.config/retroarch/config/FinalBurn Neo/fba.cfg.
[INFO] [overrides] no game-specific overrides found at /home/pi/.config/retroarch/config/FinalBurn Neo/tturfu.cfg.
[INFO] Shaders: preset directory: /home/pi/.config/retroarch/shaders/presets
[INFO] Shaders: no game-specific preset found at 

/home/pi/.config/retroarch/shaders/presets/FinalBurn Neo/tturfu.cgp.
[INFO] Shaders: no game-specific preset found at /home/pi/.config/retroarch/shaders/presets/FinalBurn 

Neo/tturfu.glslp.
[INFO] Shaders: no content-dir-specific preset found at /home/pi/.config/retroarch/shaders/presets/FinalBurn Neo/fba.cgp.
[INFO] Shaders: no content-dir-

specific preset found at /home/pi/.config/retroarch/shaders/presets/FinalBurn Neo/fba.glslp.
[INFO] Shaders: no core-specific preset found at 

/home/pi/.config/retroarch/shaders/presets/FinalBurn Neo/FinalBurn Neo.cgp.
[INFO] Shaders: no core-specific preset found at 

/home/pi/.config/retroarch/shaders/presets/FinalBurn Neo/FinalBurn Neo.glslp.
[INFO] Environ SET_SUBSYSTEM_INFO.
[INFO] Special game type: CBS ColecoVision
[INFO]   Ident: cv
[INFO]   ID: 1
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: MSX 1
[INFO]   Ident: msx
[INFO]   ID: 4
[INFO]   Content:
[INFO]     Rom (required)
[INFO] 

Special game type: Nec PC-Engine
[INFO]   Ident: pce
[INFO]   ID: 5
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Nec SuperGrafX
[INFO]   Ident: sgx
[INFO]   

ID: 7
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Nec TurboGrafx-16
[INFO]   Ident: tg16
[INFO]   ID: 9
[INFO]   Content:
[INFO]     Rom (required)
[INFO] 

Special game type: Sega GameGear
[INFO]   Ident: gg
[INFO]   ID: 2
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Sega Master System
[INFO]   Ident: sms
[INFO]   ID: 8
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Sega Megadrive
[INFO]   Ident: md
[INFO]   ID: 3
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Sega SG-1000
[INFO]   Ident: sg1k
[INFO]   ID: 6
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: ZX Spectrum
[INFO]   Ident: spec
[INFO]   ID: 10
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Special game type: Neogeo CD
[INFO]   Ident: neocd
[INFO]   ID: 11
[INFO]   Content:
[INFO]     Iso (required)
[INFO] Remaps: remap directory: /opt/retropie/configs/fba/
[INFO] Remaps: no game-specific remap found at /opt/retropie/configs/fba/FinalBurn Neo/tturfu.rmp.
[INFO] Remaps: no 

content-dir-specific remap found at /opt/retropie/configs/fba/FinalBurn Neo/fba.rmp.
[INFO] Remaps: no core-specific remap found at /opt/retropie/configs/fba/FinalBurn 

Neo/FinalBurn Neo.rmp.
[INFO] Redirecting save file to "/home/pi/RetroPie/roms/fba/tturfu.srm".
[INFO] Redirecting savestate to "/home/pi/RetroPie/roms/fba/tturfu.state".
[INFO] 

Environ GET_LOG_INTERFACE.
[INFO] Environ UNSUPPORTED (#65587).
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] CRC32: 0xa4487479 .
[libretro INFO] 

Setting save dir to /home/pi/RetroPie/roms/fba/
[INFO] Environ SYSTEM_DIRECTORY: "/home/pi/RetroPie/BIOS".
[libretro INFO] Setting system dir to /home/pi/RetroPie/BIOS
[INFO] 

Environ SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    Classic (ID: 5)
[INFO]    Modern (ID: 517)
[INFO]    Mouse (ball only) (ID: 773)
[INFO]    Mouse (full) (ID: 514)
[INFO]    Pointer (ID: 6)
[INFO]    Lightgun (ID: 4)
[INFO] Controller port: 2
[INFO]    Classic (ID: 5)
[INFO]    Modern (ID: 517)
[INFO]    Mouse (ball only) (ID: 773)
[INFO]    

Mouse (full) (ID: 514)
[INFO]    Pointer (ID: 6)
[INFO]    Lightgun (ID: 4)
[libretro INFO] Initialize DIP switches.
[INFO] Environ UNSUPPORTED (#52).
[INFO] Environ 

SET_VARIABLES.
[INFO] Environ GET_VARIABLE fbneo-cpu-speed-adjust:
[INFO] 	100%
[INFO] Environ GET_VARIABLE fbneo-allow-depth-32:
[INFO] 	enabled
[INFO] Environ 

GET_VARIABLE fbneo-vertical-mode:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE fbneo-load-subsystem-from-parent:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE fbneo-

frameskip:
[INFO] 	0
[INFO] Environ GET_VARIABLE fbneo-diagnostic-input:
[INFO] 	Hold Start
[INFO] Environ GET_VARIABLE fbneo-hiscores:
[INFO] 	enabled
[INFO] Environ 

GET_VARIABLE fbneo-samplerate:
[INFO] 	48000
[INFO] Environ GET_VARIABLE fbneo-sample-interpolation:
[INFO] 	4-point 3rd order
[INFO] Environ GET_VARIABLE fbneo-fm-

interpolation:
[INFO] 	4-point 3rd order
[INFO] Environ GET_VARIABLE fbneo-analog-speed:
[INFO] 	100%
[INFO] Environ GET_VARIABLE fbneo-cyclone:
[INFO] 	disabled
[libretro 

INFO] [FBNEO] Archive: tturfu
[libretro INFO] [FBNEO] Archive: tturf
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12266.a4 from archive 

/home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12264.a1 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] 

Using ROM with good CRC and name epr-12267.a5 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12265.a2 from archive 

/home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12268.b9 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] 

Using ROM with good CRC and name epr-12269.b10 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12270.b11 from 

archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12276.b1 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] 

[FBNEO] Using ROM with good CRC and name epr-12280.b5 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12277.b2 from 

archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12281.b6 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] 

[FBNEO] Using ROM with good CRC and name epr-12278.b3 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12282.b7 from 

archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12279.b4 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] 

[FBNEO] Using ROM with good CRC and name epr-12283.b8 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12271.a7 from 

archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12272.a8 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] 

[FBNEO] Using ROM with good CRC and name epr-12273.a9 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12274.a10 

from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro INFO] [FBNEO] Using ROM with good CRC and name epr-12275.a11 from archive /home/pi/RetroPie/roms/fba/tturfu
[libretro 

INFO] [FBNEO] Using ROM with good CRC and name 317-0099.c2 from archive /home/pi/RetroPie/roms/fba/tturfu
[INFO] Environ GET_VARIABLE fbneo-dipswitch-tturfu-Continues:
[INFO] 	

None
[INFO] Environ GET_VARIABLE fbneo-dipswitch-tturfu-Difficulty:
[INFO] 	Normal
[INFO] Environ GET_VARIABLE fbneo-dipswitch-tturfu-Starting_Energy:
[INFO] 	6
[INFO] Environ GET_VARIABLE fbneo-dipswitch-tturfu-Demo_Sounds:
[INFO] 	On
[INFO] Environ GET_VARIABLE fbneo-dipswitch-tturfu-Bonus_Energy:
[INFO] 	2
[INFO] Environ 

GET_VARIABLE fbneo-dipswitch-tturfu-Coin_A:
[INFO] 	1 Coin  1 Credit
[INFO] Environ GET_VARIABLE fbneo-dipswitch-tturfu-Coin_B:
[INFO] 	1 Coin  1 Credit
[libretro 

INFO] [Cheevos] System RAM set to 0x6e1a6008 94208
[INFO] Environ SET_ROTATION: 0
[INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
[libretro INFO] Driver tturfu was successfully 

started : game's full name is Tough Turf (set 1, US, 8751 317-0099)
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: 

Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ 897x672
[INFO] [Video]: Starting threaded video driver ...
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: 

EGL version: 1.4
[INFO] [EGL]: Current context: 0x1.
[INFO] [GL]: Found GL context: videocore
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [EGL]: eglSwapInterval

(1)
[INFO] [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
[INFO] [GL]: Version: OpenGL ES 2.0.
[INFO] Querying EGL extension: KHR_image => exists
[WARN] [GL]: GLES 

implementation does not have BGRA8888 extension.
32-bit path will require conversion.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] 

[GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] 

[GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] 

[GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] Resetting shader to defaults ... 
[INFO] [GL]: Using 4 textures.
[INFO] 

[GL]: Loaded 1 program(s).
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a 

suitable driver.
[INFO] [udev]: Keyboard #0 (/dev/input/event0).
[INFO] [udev]: Keyboard #1 (/dev/input/mouse0).
[INFO] [udev]: Mouse #0 (/dev/input/event0).
[INFO] [udev]: Mouse 

#1 (/dev/input/mouse0).
[INFO] [Joypad]: Found joypad driver: "udev".
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [Video]: Found display server: null
[INFO] 

Found shader "/home/pi/.config/retroarch/shaders/2xsal-level2-crt.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/2xsal.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/2xScaleHQ.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/barrel-distortion.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/barrel-distortion_lanczos4.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/barrel-distortion_phosphor.glslp"
[INFO] Found 

shader "/home/pi/.config/retroarch/shaders/barrel-distortion_snes.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/Brighter-with_Contrast.glslp"
[INFO] Found 

shader "/home/pi/.config/retroarch/shaders/bsnes_gamma_ramp.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/crt-pi-curvature-vertical.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/crt-pi-curvature.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/crt-pi-vertical.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/crt-pi.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/gameboy-screen-grid.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/gameboy.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/gameboy2.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/gba-color.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2x&lcd3x.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/hq2x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2x2.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/hq2x_lcd3x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2x_phosphor.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/hq2xwaterpaint.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2xwaterpaintscanline.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/hq4x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq4x_lcd3x.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/nds-color.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/nds.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/nedi.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/palm-color.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/phosphor.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/psp-color.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/sharp-bilinear-2x-prescale.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/sharp-bilinear-scanlines.glslp"
[INFO] Found 

shader "/home/pi/.config/retroarch/shaders/sharp-bilinear-simple.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/snes2.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_hq2x.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/snes_hq2xwaterpaint.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_hq2xwaterpainthicontrast.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/snes_hq2xwaterpaintscanline.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_lcd3x.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/snes_phosphor.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_scanline.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/snes_waterpaint.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/stock.glsl"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/super-2xsai.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/super-eagle.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/vba-color.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/xbr-lv1-noblend.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/zfast_crt_curve.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/zfast_crt_curve_vertical.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/zfast_crt_standard.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/zfast_crt_standard_vertical.glslp"
[INFO] Found shader 

"/home/pi/.config/retroarch/shaders/zfast_lcd_standard.glslp"
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 

frames
[INFO] Environ SET_SUBSYSTEM_INFO.
[INFO] Subsystem ID: 0
[INFO] Special game type: CBS ColecoVision
[INFO]   Ident: cv
[INFO]   ID: 1
[INFO]   Content:
[INFO]     Rom 

(required)
[INFO] Subsystem ID: 1
[INFO] Special game type: MSX 1
[INFO]   Ident: msx
[INFO]   ID: 4
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Subsystem ID: 2
[INFO] Special 

game type: Nec PC-Engine
[INFO]   Ident: pce
[INFO]   ID: 5
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Subsystem ID: 3
[INFO] Special game type: Nec SuperGrafX
[INFO]   

Ident: sgx
[INFO]   ID: 7
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Subsystem ID: 4
[INFO] Special game type: Nec TurboGrafx-16
[INFO]   Ident: tg16
[INFO]   ID: 9
[INFO]   

Content:
[INFO]     Rom (required)
[INFO] Subsystem ID: 5
[INFO] Special game type: Sega GameGear
[INFO]   Ident: gg
[INFO]   ID: 2
[INFO]   Content:
[INFO]     Rom (required)
[INFO] 

Subsystem ID: 6
[INFO] Special game type: Sega Master System
[INFO]   Ident: sms
[INFO]   ID: 8
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Subsystem ID: 7
[INFO] Special 

game type: Sega Megadrive
[INFO]   Ident: md
[INFO]   ID: 3
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Subsystem ID: 8
[INFO] Special game type: Sega SG-1000
[INFO]   Ident: 

sg1k
[INFO]   ID: 6
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Subsystem ID: 9
[INFO] Special game type: ZX Spectrum
[INFO]   Ident: spec
[INFO]   ID: 10
[INFO]   Content:
[INFO]     Rom (required)
[INFO] Subsystem ID: 10
[INFO] Special game type: Neogeo CD
[INFO]   Ident: neocd
[INFO]   ID: 11
[INFO]   Content:
[INFO]     Iso (required)
[INFO] 

Subsystems: 11
[INFO] [LED]: LED driver = 'null' 0x2336bc
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized 

"alsa" driver.
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, User 1, Button "Y (left)" => "Fire 

3"
[INFO] 	RetroPad, User 1, Button "Select" => "Coin 1"
[INFO] 	RetroPad, User 1, Button "Start" => "Start 1"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 1, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, User 2, Button "Y (left)" => "Fire 

3"
[INFO] 	RetroPad, User 2, Button "Select" => "Coin 2"
[INFO] 	RetroPad, User 2, Button "Start" => "Start 2"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 2, Button "A (right)" => "Fire 2"
[INFO] Loading history file: [/opt/retropie/configs/fba/content_history.lpl].
[INFO] Loading history file: 

[/opt/retropie/configs/fba/content_favorites.lpl].
[INFO] Loading history file: [/opt/retropie/configs/fba/content_music_history.lpl].
[INFO] Loading history file: 

[/opt/retropie/configs/fba/content_video_history.lpl].
[INFO] Loading history file: [/opt/retropie/configs/fba/content_image_history.lpl].
[INFO] Written to playlist file: 

/opt/retropie/configs/fba/content_history.lpl
```

**Comment by barbudreadmon** [comment] 2019-10-07 05:18
ok, i misunderstood your first instructions, actually i can reproduce this issue on any arch, the game is indeed freezing at the start of attract mode, reopening.

**Comment by barbudreadmon** [comment] 2019-10-27 14:54
Fixed

**Closed by barbudreadmon** 2019-10-27 14:54 UTC

**Comment by Wilstorm** [comment] 2019-10-29 21:04
@barbudreadmon - It looks good here! It seems many of the older cores have graphical glitches so it's nice to see an English version working too. Many thanks for fixing this classic! :)
