### ISSUE TITLE
Some new games doesn't work on PS3

### ISSUE THREAD

**Issue by crystalct** [libretro/FBNeo#400] opened 2020-07-15 21:02 UTC
3on3dunk, actionhw, aoh, armchmp2, bigrun, blocken, boonggab, candy etc etc
It seems FBneo stopped to support PS3.....

**Comment by barbudreadmon** [comment] 2020-07-15 22:12
> It seems FBneo stopped to support PS3.....

Yes, it did, this emulator is actually for windows x86, it always was, there has been maintainers for other platforms but no one works on ps3 support at the moment. Even if @dinkc64 managed to blindfix some issues through **accurate information**, it's still a hard task, and the "it doesn't work" kind of report won't help much...

**Comment by dinkc64** [comment] 2020-07-15 23:34
With CaptainCPS gone, there is nobody on the team with a PS3 that can even make the specialized fixes just for this hardware.
I don't have a PS3 or any game console for that matter, so I can only guess what needs to be done to fix them based on previous work by CaptainCPS and others, and only if we know they're broken.  Also some games we can't fix or won't try to fix, or even don't know how to fix, because they're too demanding to even work on a PS3 or other big endian HW.

**Comment by crystalct** [comment] 2020-07-16 06:07
Some games start in blak screen other like this (3on3dunk):
![image](https://user-images.githubusercontent.com/1675181/87632036-d989bc80-c738-11ea-8308-e5ad8b254267.png)
or this (actionhw):
![image](https://user-images.githubusercontent.com/1675181/87632345-8106ef00-c739-11ea-9af1-c1122622ce50.png)
It is a pity that FB Neo libretro core is diverging from the PS3 scene, it's the best retroarch/libretro core (imho). I tried to continue CaptainCPS 's work, FB Neo RL for PS3 was released and now FB Neo RL plus 2.0. Ps3 is a great machine for Homebrew, i know, ostic to develop and with a curse..... The Big Endian curse. Probably it's the only machine on Retroarch scene with that curse. I can give my little help in some way

**Comment by barbudreadmon** [comment] 2020-07-16 07:14
> Probably it's the only machine on Retroarch scene with that curse

That's the curse of that generation, xbox360 and wii/wiiu use ppc cpus too. I believe the ps3 is a lot more powerful than the 2 others though.

**Comment by SumavisionQ5** [comment] 2020-07-17 09:08
> With CaptainCPS gone, there is nobody on the team with a PS3 that can even make the specialized fixes just for this hardware.
> I don't have a PS3 or any game console for that matter, so I can only guess what needs to be done to fix them based on previous work by CaptainCPS and others, and only if we know they're broken. Also some games we can't fix or won't try to fix, or even don't know how to fix, because they're too demanding to even work on a PS3 or other big endian HW.

Is CaptainCPS alive?

**Comment by crystalct** [comment] 2020-07-17 09:13
Something serious must have happened to him... he has disappeared from all the scenes where he was active and has never replied to messages and emails.

**Comment by dinkc64** [comment] 2020-07-17 13:36
The bad feeling I get when I say this:  he disappeared a few days before the hurricane blew apart Puerto Rico - his homeland.  :(

**Comment by SumavisionQ5** [comment] 2020-07-18 01:20
Sorry to hear that :(

**Comment by barbudreadmon** [comment] 2020-07-19 08:01
@crystalct dink pushed some big endian fixes for 3on3dunk and actionhw, please test them and let us know if they have still issues.

**Comment by crystalct** [comment] 2020-07-19 11:49
I will

**Comment by crystalct** [comment] 2020-07-19 17:00
Now is better, but not solved entirely.
3on3dunk:
![image](https://user-images.githubusercontent.com/1675181/87880380-9017c680-c9f1-11ea-8905-cb96d4aee1e9.png)
![image](https://user-images.githubusercontent.com/1675181/87880410-c2c1bf00-c9f1-11ea-80c2-33745247fc30.png)
![image](https://user-images.githubusercontent.com/1675181/87880424-da00ac80-c9f1-11ea-8178-30b6f5de09eb.png)

actionhw, no:
![image](https://user-images.githubusercontent.com/1675181/87880453-16cca380-c9f2-11ea-9b9e-c6b3e4daf474.png)

**Comment by crystalct** [comment] 2020-07-19 17:12
bigrun:
![image](https://user-images.githubusercontent.com/1675181/87880545-cb66c500-c9f2-11ea-990c-896dcca2a5c6.png)

cischeat:
![image](https://user-images.githubusercontent.com/1675181/87880584-15e84180-c9f3-11ea-9606-cf8d8fdc6082.png)

f1gpstar:
![image](https://user-images.githubusercontent.com/1675181/87880648-a888e080-c9f3-11ea-9f51-fdc0c605fdbb.png)

f1gpstr2:
![image](https://user-images.githubusercontent.com/1675181/87880668-d1a97100-c9f3-11ea-914c-5c80f64b6d44.png)

etc etc

**Comment by dinkc64** [comment] 2020-07-20 01:03
Hi crystalct,
I checked in another update for 3on3 and actionhw, please give em a try when you get a chance :)
bigrun will have to come later, that driver will be a massive undertaking!

best regards,
- dink

**Comment by crystalct** [comment] 2020-07-20 06:50
Now 3on3 is:
![image](https://user-images.githubusercontent.com/1675181/87907839-a52e3d00-ca65-11ea-9b81-ec7f50b71054.png)
![image](https://user-images.githubusercontent.com/1675181/87907889-bc6d2a80-ca65-11ea-8bf7-8b745e11c1bc.png)
![image](https://user-images.githubusercontent.com/1675181/87907910-c98a1980-ca65-11ea-875b-33b53626be6f.png)
![image](https://user-images.githubusercontent.com/1675181/87908003-fdfdd580-ca65-11ea-8610-7cbbbdcbcf9f.png)
![image](https://user-images.githubusercontent.com/1675181/87907733-6b5d3680-ca65-11ea-98aa-6da0b19465c4.png)
![image](https://user-images.githubusercontent.com/1675181/87907785-82038d80-ca65-11ea-841e-8637a0c569aa.png)

**Comment by crystalct** [comment] 2020-07-20 06:51
actionhw:
![image](https://user-images.githubusercontent.com/1675181/87908145-3ac9cc80-ca66-11ea-811d-7f8f7a50000a.png)

**Comment by dinkc64** [comment] 2020-07-20 13:14
hmm, looks exactly the same - are you sure you have the latest code compiled in there?

**Comment by crystalct** [comment] 2020-07-20 16:10
Now it seems perfect ^_^
![image](https://user-images.githubusercontent.com/1675181/87960271-5956b480-cab4-11ea-9fca-6b620a54fec3.png)

**Comment by crystalct** [comment] 2020-07-20 17:41
actionhw changed a bit:
![image](https://user-images.githubusercontent.com/1675181/87968577-eef84100-cac0-11ea-836f-d8c935d42662.png)

**Comment by dinkc64** [comment] 2020-07-20 23:44
great :)  I will try again later tonight with actionhw.

**Comment by barbudreadmon** [comment] 2020-07-21 07:30
@crystalct Do you have a guide or something to build "FB NEO RL Plus" ? (something i can use on linux)
It would certainly help debugging if i could build this stuff myself, i already have the rpcs3 setup.

On a sidenote, there is a new attempt at fixing actionhw on git.

**Comment by crystalct** [comment] 2020-07-21 09:30
Well, FB NEO RL Plus (my version, original was FB Alpla RL from Captain CPS) is a Retro loader. It manage libretro cores and retroarc layer.
For testing FB NEO RL Plus it's not essential. You need a SDK SONY environment to compile fbneo and retroarch layer and then RPCS3 emulator (or a PS3 homebrew capable).
Free PSL1GHT SDK, used to compile FB NEO RL (https://github.com/crystalct/FBNeoRLPlus), isn't good to compile retroarch and cores, too many issues. Them can coexist because FB Neo RL calls elf bin made with SONY SDK. 
If you want setup a tiny mingw with both (SONY sdk and PSL1GHT sdk) i can help you.

**Comment by barbudreadmon** [comment] 2020-07-21 09:56
There is no linux version for those sdks ?

Main issue with installing a ppc linux machine though qemu/kvm is that i might end up having tons of additional issues, is retroarch even able to run on ppc linux ? Are there even linux distro that still provide support for ppc ?

**Comment by crystalct** [comment] 2020-07-21 10:12
maybe this: https://www.debian.org/ports/powerpc/index.it.html

**Comment by crystalct** [comment] 2020-07-21 10:29
actionhw:
![image](https://user-images.githubusercontent.com/1675181/88043214-72f80a80-cb4d-11ea-8940-cff2b3cbbc38.png)

![image](https://user-images.githubusercontent.com/1675181/88043425-b2bef200-cb4d-11ea-878c-8854cacc06bc.png)

![image](https://user-images.githubusercontent.com/1675181/88043532-d5e9a180-cb4d-11ea-92e8-91649c8f601d.png)

**Comment by barbudreadmon** [comment] 2020-07-21 10:52
i'll try the qemu-ppc approach, if it works it'll be the easiest method

**Comment by crystalct** [comment] 2020-07-21 10:59
Maybe my PS3 colleague @bucanero has a linux virtual machine with SDK sony, ready to use....

**Comment by bucanero** [comment] 2020-07-21 13:13
> Maybe my PS3 colleague @bucanero has a linux virtual machine with SDK sony, ready to use....

hello @crystalct , I'm sorry but I don't have any linux VM; I know from the psdevwiki that there was a leak of the linux SDK (I think version 4.0) but I have never seen it at all. I have only seen the leaked windows SDK in torrents and file sharing links, like you said.

Hunting for those Linux files might be a challenge, as it seems everyone building homebrew was always using Windows (mingw , cygwin, leaked sdk, etc). I guess your suggestion of a windows VM could be an option too.

**Comment by crystalct** [comment] 2020-07-23 22:11
@barbudreadmon how is going qemu-ppc approach?

**Comment by barbudreadmon** [comment] 2020-07-23 23:11
@crystalct bad, tbh i gave up, it's way too slow and there were tons of issues building fbneo on it.

**Comment by barbudreadmon** [comment] 2020-07-24 09:16
@crystalct i managed to get psl1ght working on linux (the controller issue won't be a problem since i can use keyboard for my tests), now if someone can tell me what i'm supposed to do to turn the `fbneo_libretro_psl1ght.a` i built into a pkg i can use in rpcs3, i should be ready to test things on my own.

**Comment by crystalct** [comment] 2020-07-24 11:31
I'm out this weekend for a vacation. When i will return, i will be happy to
help.

Il ven 24 lug 2020, 11:17 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by crystalct** [comment] 2020-07-24 11:38
Git clone libretro/RetroArch
Put compiled library into RetroArch folder renaming It correctly
make -f Makefile.ps3 platform=psl1ght

Il ven 24 lug 2020, 11:17 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by crystalct** [comment] 2020-07-24 12:09
Or maybe Make -f Makefile.psl1ght

Il gio 16 lug 2020, 00:13 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by barbudreadmon** [comment] 2020-07-24 13:40
Building retroarch is failing atm (because of some recent major changes in the psl1ght headers among other things), i "tried" fixing those, but the .elf i got just freezed rpcs3, this is just way too much of a hassle for fixing big endian issues, aka something that'll NEVER be useful again, even the recent ppc cpus are little endian.

I'll wait for fixes and guide before trying again.

**Comment by crystalct** [comment] 2020-07-24 14:07
Psl1ght compilation produces 2 files, .Elf and .self .....Elf files never
worked, the right Once Is self.

Il ven 24 lug 2020, 15:40 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by barbudreadmon** [comment] 2020-07-24 15:22
Finally got it running, it's producing 3 files btw, the one to start is "retroarch_psl1ght.fake.self".

**Comment by crystalct** [comment] 2020-07-24 15:29
Right, Also fake.self Is produced, but It should not work...strange.

**Comment by crystalct** [comment] 2020-07-25 17:11
So, home compiled RetroArch/fbneo with psl1ght Is usable. Good.

Il ven 24 lug 2020, 17:22 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by crystalct** [comment] 2020-07-26 12:20
Another one not working... x2222 (black screen).

**Comment by dinkc64** [comment] 2020-07-26 13:50
at this point you can consider any non-8bit game to not work on a big endian system without special big-endian fixes

**Comment by crystalct** [comment] 2020-07-26 14:36
I'm not so pessimistic. galastrm and md_sf2re, just added, work correctly on PS3.

**Comment by dinkc64** [comment] 2020-07-27 12:15
Of course, there will be contradictions to what I said in 2 cases:
It's a game that has been added to an already BE-working driver.
A new driver that uses shared components/chips with already BE-working systems (Taito)

**Comment by crystalct** [comment] 2020-07-28 07:21
Wanting to try to help a bit about Big Endian Issue, every data type read/written from/to file system (eproms) with length egual or greater than 16 Bit, must be processed by BURN_ENDIAN_SWAP_INT functions, right?

**Comment by barbudreadmon** [comment] 2020-07-28 07:38
m68k is already ok, that cpu core is quite old, it's more tricky for games that use new cpu cores, i gave a try to BURN_ENDIAN_SWAP_INT in the driver for aoh but still got a black screen, most likely qs1000 & e132xs need to be fixed first (and i've no idea how to do that). fwiw it's what i tried : https://pastebin.com/raw/SwGpePNy

**Comment by crystalct** [comment] 2020-07-28 07:53
So, there some games that have CPU emulated well, but must be tuned its specific drive, for example bigrun. It's a M68k game and it's good start point for me.

**Comment by crystalct** [comment] 2020-07-28 13:27
As a first attempt, it is not bad:

![image](https://user-images.githubusercontent.com/1675181/88671506-a820d180-d0e6-11ea-8af2-f77e7f61ddcb.png)

![image](https://user-images.githubusercontent.com/1675181/88671562-bb33a180-d0e6-11ea-86a7-aced84aa0c98.png)

**Comment by crystalct** [comment] 2020-07-28 13:57
Ok.... sound and accelerator button dont work....

**Comment by crystalct** [comment] 2020-07-28 15:44
i will test it

**Comment by barbudreadmon** [comment] 2020-07-28 16:02
attract is what's looping as long as you don't insert coins, so title screen + some gameplay + animations

**Comment by crystalct** [comment] 2020-07-28 19:33
aoh:

![image](https://user-images.githubusercontent.com/1675181/88712074-7117e380-d119-11ea-9ab4-0d5aadeb001a.png)

![image](https://user-images.githubusercontent.com/1675181/88712225-ad4b4400-d119-11ea-8d0a-b1cb1550b1b1.png)

![image](https://user-images.githubusercontent.com/1675181/88712350-dd92e280-d119-11ea-9406-152e226fc89e.png)

Compliments!!!!
![image](https://user-images.githubusercontent.com/1675181/88712429-ff8c6500-d119-11ea-8bb4-a236ab3a082f.png)

**Comment by crystalct** [comment] 2020-07-28 21:19
dblewing needs a little big endian tuning.

![image](https://user-images.githubusercontent.com/1675181/88723220-c1e30880-d128-11ea-916e-ff23b2b2356c.png)

**Comment by barbudreadmon** [comment] 2020-07-29 10:27
With the latest fix, colors are ok but tiles are flashing
![dblewing-200729-102326](https://user-images.githubusercontent.com/10391265/88789071-8ed75e00-d196-11ea-8fae-f53be935b72c.png)
(on a sidenote, it seems the psl1ght version doesn't support rotation)

**Comment by barbudreadmon** [comment] 2020-07-29 15:40
dblewing seems ok with latest commit

**Comment by crystalct** [comment] 2020-07-29 18:04
![image](https://user-images.githubusercontent.com/1675181/88835812-17292380-d1d6-11ea-821c-e8186270ed3e.png)

![image](https://user-images.githubusercontent.com/1675181/88835937-43dd3b00-d1d6-11ea-99b6-b15bbdb02954.png)

![image](https://user-images.githubusercontent.com/1675181/88836081-77b86080-d1d6-11ea-9bb4-34b68fc0e9b5.png)

A question.. back to bigrun....
One or two buttons aren't working (also sound). Is possible that big endian issue can affect buttons pads?

**Comment by barbudreadmon** [comment] 2020-07-30 07:08
> Is possible that big endian issue can affect buttons pads?

There is no exception, as long as 16/32 bits pointers are involved it can happen.

**Comment by barbudreadmon** [comment] 2020-07-30 09:15
re-bigrun buttons : i believe the problem is related to the implicit cast from UINT8 to UINT16 in `bigrun_ip_select_read` for analog controls (`ProcessAnalog` is returning an UINT8), at the very least i'm pretty sure `bigrun_ip_select_read` isn't returning something usable on big endian (same issue with `cischeat_ip_select_r`)

**Comment by crystalct** [comment] 2020-07-30 10:53
Analogs are the culprits. I add right big endian function on wildplt game
and now graphics works, but analog input dean't work.

Il giorno gio 30 lug 2020 alle ore 11:16 barbudreadmon <
notifications@github.com> ha scritto:

**Comment by crystalct** [comment] 2020-07-30 11:33
I putted `printf("%d - %d - %d - %d\n",  Analog0, Analog1, Analog2, Analog3);` inside `bigrun_ip_select_read()` and when i press accelerator button only Analog2 change (from 1 to -1). The problem is that there isn't Analog2:

```
	switch (ip_select & 3)
	{
		case 0 : return ProcessAnalog(Analog0, 0, INPUT_DEADZONE, 0x00, 0xff);
		case 3 : return ProcessAnalog(Analog1, 0, INPUT_DEADZONE | INPUT_LINEAR | INPUT_MIGHTBEDIGITAL, 0x00, 0xff);
	}
```

**Comment by crystalct** [comment] 2020-07-30 13:35
What is the source code where AnalogX values ​​are read?

**Comment by crystalct** [comment] 2020-07-30 14:20
Solved Analog problem. The solution (HIDDEN) is inside d_lordgun.cpp.
Analogs must be INT32 and then:

```
BurnGunMakeInputs(0, (INT16)Analog0, -(INT16)Analog1); // reversed y axis
BurnGunMakeInputs(1, (INT16)Analog2, (INT16)Analog3);
```

**Comment by barbudreadmon** [comment] 2020-07-30 14:20
It turns out that using INT32 instead of INT16 type for the AnalogX variables fix this issue, i believe it's related to how the following codepath for big endian archs : 
https://github.com/libretro/FBNeo/blob/27dd85fab8e07f15a0daaeb06427cb1cb259b34f/src/burner/libretro/retro_input.cpp#L2386

Maybe there is a better way to handle this code (that code is something i inherited from the original port), i'll inquire dink about this when i see him.

**Comment by barbudreadmon** [comment] 2020-07-30 14:21
ahah, we reached the same solution at the same time

**Comment by crystalct** [comment] 2020-07-30 14:21
LOL 
Contemporaneous!!!

https://sdk.bitmoji.com/render/panel/a6333955-5854-4f7d-9675-f17bf07fce90-888af1ad-9072-4a68-8915-4e015bf57555-v1.png?transparent=1&palette=1

**Comment by dinkc64** [comment] 2020-07-30 16:48
Inputs must not be int32, I will fix it the proper way :)

**Comment by dinkc64** [comment] 2020-07-30 17:03
proper fix: retro_input.cpp:2386

find:
#ifdef LSB_FIRST
				*(pgi->Input.pShortVal) = pgi->Input.nVal;
#else
				*((int *)pgi->Input.pShortVal) = pgi->Input.nVal;
#endif

replace with:
				*(pgi->Input.pShortVal) = pgi->Input.nVal;

**Comment by crystalct** [comment] 2020-07-30 17:29
That solve onluy x/y axis movements or analog buttonts too?

Il gio 30 lug 2020, 19:03 dinkc64 <notifications@github.com> ha scritto:

**Comment by barbudreadmon** [comment] 2020-07-30 20:09
It should be ok with latest commits, it turns out that removing this hack required to turn every INT32 analogs into an INT16.

NB : we might have missed some

**Comment by barbudreadmon** [comment] 2020-07-30 20:41
https://github.com/finalburnneo/FBNeo/commit/d8ec76ad57e453499178b406f5d51146ce77c71a seems to fix sound for cischeat driver

**Comment by crystalct** [comment] 2020-07-30 21:52
I'll try them tomorrow morning 
![image](https://user-images.githubusercontent.com/1675181/88978297-ba099c80-d2bf-11ea-8898-2e47627c2b6f.png)

**Comment by barbudreadmon** [comment] 2020-07-31 05:50
blocken seems ok with https://github.com/finalburnneo/FBNeo/commit/38508ef8ca1aa19a03f414c4fe815249a5b6408f

**Comment by barbudreadmon** [comment] 2020-07-31 06:24
candy seems ok with https://github.com/finalburnneo/FBNeo/commit/4d860e743cbbe8779952a50dadfa11bbef080cc1

@crystalct I believe with so many example you should be ok fixing most big-endian issues by yourself now and should ask help only when you are in a bind. The general rule is to search for access to casted pointers, basically, search "(UINT" in a file and you'll most likely find them. Please close this issue after you confirmed the latest fixes.

**Comment by crystalct** [comment] 2020-07-31 10:28
Yes Sir! On my way! ^_^

Bigrun OK
Cisheat OK, 
Wildplt OK, except graphics, it needs a little tuning
Mwalk OK
Mplanet OK
Outrun OK
DDay OK
Capbowl OK
Lethalen, analogs ok but only viewfinder is visible, graphics not working (endian isssue investigation)
Foodf, analogs ok but need Endian tuning
Tceptor, analogs ok but need Endian tuning
bbusters, analogs ok but only viewfinder is visible, graphics not working (endian isssue investigation)
Momoko OK
Macross2 OK
Blocken needs Endian tuning
Boonggab OK
Candy needs Endian tuning
Coolmini OK
Crazywar needs Endian tuning
Dquizgo2 OK
Dtfamily OK
Dynabomb needs Endian tuning
F1gpstar needs Endian tuning
F1gpstr2 needs Endian tuning
Finalgdr OK
Fort2b needs Endian tuning
Galpani3 needs Endian tuning
Gstream needs Endian tuning
Heberpop needs Endian tuning
Hidctch2 needs Endian tuning
Hidctch3 needs Endian tuning
Hidnctch needs Endian tuning
Hotchase needs Endian tuning
Hyperduel needs Endian tuning
Inufuku OK
Ironfort needs Endian tuning
Jmpbreak OK
Kickgoa OK
Killbld rom check fail, needs Endian tuning
Killbld104 rom check fails, needs Endian tuning
Klondkp OK
Landbrk OK
Legendoh needs Endian tuning
Linkypip needs Endian tuning
Magerror needs Endian tuning
Misncrft OK
Mosaicf2 needs Endian tuning
Mrdig OK
Mrkicker OK
Newxpang OK
Nhidctch needs Endian tuning
Pasha2 needs Endian tuning
Penfan needs Endian tuning
Poosho OK
Puzzlekg OK
Puzzli needs Endian tuning
Rabbit needs Endian tuning
Raccoon graphics OK, sound isn't good
Sb2003 needs Endian tuning
Scudhamm doesn't work on PS3 and X86
Shangha3 needs Endian tuning
Spotty needs Endian tuning
Stealsee needs Endian tuning
Suplup OK
Toyland OK
Vamphalf OK
Wecleam needs Endian tuning
Wivernwg OK
Worldadv OK

**Closed** 2020-07-31 10:29 UTC

**Comment by barbudreadmon** [comment] 2020-07-31 12:02
> Blocken needs Endian tuning
Shangha3 needs Endian tuning

Hmmm what's wrong with those 2 ? They seemed fine after my fix

**Comment by crystalct** [comment] 2020-08-01 19:37
Blocken:

![image](https://user-images.githubusercontent.com/1675181/89109099-87d27900-d43e-11ea-9d07-c05fdc362402.png)

Shangha3
![image](https://user-images.githubusercontent.com/1675181/89109137-ccf6ab00-d43e-11ea-8d32-cdf4defbe4a2.png)

Candy:
![image](https://user-images.githubusercontent.com/1675181/89109180-2eb71500-d43f-11ea-8db7-d78f41fbe616.png)

**Comment by barbudreadmon** [comment] 2020-08-01 20:44
It is weird, those games are fine on my side

**Comment by barbudreadmon** [comment] 2020-08-01 20:56
Did you try deleting nvrams ?

**Comment by crystalct** [comment] 2020-08-02 05:38
No.....how?

Il sab 1 ago 2020, 22:57 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by barbudreadmon** [comment] 2020-08-02 06:50
the .fs & .nv files in your savefiles/fbneo/ folder, but only candy seems to have a file in there, sorry but i don't know what could be your problem, i checked those games several times, both playing them and looking through their code, i don't see any issue, it might be a problem with the fb neo rl plus frontend or the sony sdk, you'll have to investigate, all i can say is that everything is fine using psl1ght + RA.

**Comment by crystalct** [comment] 2020-08-02 06:54
I will see the difference betwen psl1ght code and Sony SDK code.

Il dom 2 ago 2020, 08:50 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by dinkc64** [comment] 2020-08-02 13:21
please try beast busters and mechanized attack, I made a possible endian fix for it last night.

**Comment by crystalct** [comment] 2020-08-02 14:16
Of course

Il dom 2 ago 2020, 15:21 dinkc64 <notifications@github.com> ha scritto:

**Comment by crystalct** [comment] 2020-08-02 22:14
Blocken was OK, you have to wait all checks... then the graphics is perfect:
![image](https://user-images.githubusercontent.com/1675181/89132706-6d6bce80-d516-11ea-84e8-971bb40f88bb.png)

Shanga was OK....
![image](https://user-images.githubusercontent.com/1675181/89132800-23371d00-d517-11ea-9a9e-c9d1d65eaa37.png)

Candy was OK....
![image](https://user-images.githubusercontent.com/1675181/89132895-c12ae780-d517-11ea-89f1-2964035c43da.png)

I suspect a my mistake on updating FBneo repository, i'm sorry.

Bbuster OK
![image](https://user-images.githubusercontent.com/1675181/89133486-7eb7d980-d51c-11ea-8694-a9345a5542ca.png)

Mechatt OK
![image](https://user-images.githubusercontent.com/1675181/89133545-000f6c00-d51d-11ea-87ea-ee74ebd73750.png)

I cann't belive ittttttttttt
NEO CD WORKKSSSS!!!!
Rally Chase OK
![image](https://user-images.githubusercontent.com/1675181/89133692-3d282e00-d51e-11ea-8fd3-0be8c5bda974.png)
![image](https://user-images.githubusercontent.com/1675181/89133598-7f9d3b00-d51d-11ea-8c7b-8ddc0dd60e5d.png)
![image](https://user-images.githubusercontent.com/1675181/89133615-9fccfa00-d51d-11ea-9569-7a1955a951c1.png)

Project NEON OK
![image](https://user-images.githubusercontent.com/1675181/89133699-5335ee80-d51e-11ea-92e1-8a682ca9ecac.png)

**Comment by barbudreadmon** [comment] 2020-08-03 05:13
@crystalct re neocd : you got the cracklings too ?

**Comment by crystalct** [comment] 2020-08-03 06:10
I think the volume was 0.... i'll try

**Comment by crystalct** [comment] 2020-08-03 10:13
Yes, certain sfx sounds aren't good

**Comment by crystalct** [comment] 2020-08-04 21:34
I'm not able to fix Asterix (Konami)... i need help.

**Comment by barbudreadmon** [comment] 2020-08-04 22:50
i'll look at it if i'm ever finished with fixing pgm's sound, did you look at konamiic.cpp ?

**Comment by crystalct** [comment] 2020-08-05 05:51
Maybe K056832.cpp

**Comment by barbudreadmon** [comment] 2020-08-05 09:21
imho, if you don't find it, try harder, i probably spent several dozens of hours over the last 5 days testing things for pgm (which seems finally fixed with https://github.com/libretro/FBNeo/commit/a18eb560db402923201cb2a70c7cf6901ca89131), i had to print all kinds of values and compare with x86 until i found out what was acting weird, then finding the root of it, and even then i ended up having to figure out a fix of my own, since no one on internet seems to mention a big-endian issue with this...

anyway i might take a look at https://github.com/finalburnneo/FBNeo/issues/191 , and after that i think i'll do a pause big-endian issues

**Comment by crystalct** [comment] 2020-08-05 11:03
i'm am full immersion on k0xxxxx.cpp of konami. I changed target, d_bishi.cpp rather than d_asterix.cpp because it seems near to work.... but nothing... K053245.cpp and K053247.cpp are written better and they work. K056832.ccp is a pain.

**Comment by crystalct** [comment] 2020-08-30 23:08
@barbudreadmon @dinkc64 
if *pix is a UINT16 pointer, what is the correct use of BURN_ENDIAN_SWAP_INT16 with this:
`*pix |= (tile & 0x0ff00000) >> 16;`

**Comment by dinkc64** [comment] 2020-08-31 00:02
Usually stuff like that doesn't get swapped :)

**Comment by crystalct** [comment] 2020-08-31 16:59
I thinked no.... so i tested:
X86 example (memory contain 00 5a - tile 0x1f1b280): 
 *pix: 0x5a -> 0x15a  so memory now is 01 5a
PS3 same conditions:
*pix: 0x5a00 -> 0x5b00 so memery become 00 5b

**Comment by crystalct** [comment] 2020-08-31 17:29
The answer is:
`*pix |= BURN_ENDIAN_SWAP_INT16((tile & 0x0ff00000) >> 16);`

![bitmoji](https://sdk.bitmoji.com/render/panel/7107105a-eaab-4172-99d6-25e0a200a300-888af1ad-9072-4a68-8915-4e015bf57555-v1.png?transparent=1&palette=1&width=246)

**Comment by barbudreadmon** [comment] 2020-08-31 17:33
yes, iirc i did this in another driver, `(tile & 0x0ff00000) >> 16` value should be the same on both arch, so you need to swap it before feeding it to the 16bits pointer

**Comment by dinkc64** [comment] 2020-08-31 18:44
oh, alright then :)

**Comment by crystalct** [comment] 2020-09-07 21:29
FInally i win!!!
![image](https://user-images.githubusercontent.com/1675181/92417210-5b0e3180-f161-11ea-8b22-8e63b24003c5.png)

![image](https://user-images.githubusercontent.com/1675181/92417214-619ca900-f161-11ea-85a4-644be4e59af1.png)

Now i have to clean all tests, remove all unnecessary code and make a correct PR, but after a bit of rest.

**Comment by dinkc64** [comment] 2020-09-07 23:14
nice :)
