### ISSUE TITLE
asteroids deluxe dont support 2nd player start keys and the color is white..it must be light blue as i read in the wikipedia.

### ISSUE THREAD

**Issue by kounabi22** [libretro/FBNeo#1039] opened 2023-02-26 14:47 UTC
Asteroids deluxe dont support 2nd player keys...and the colors are white...it must be light blue as i read in the wikipedia..

**Comment by barbudreadmon** [comment] 2023-02-27 07:13
Duplicate of https://github.com/finalburnneo/FBNeo/issues/1355

**Closed by barbudreadmon** 2023-02-27 07:13 UTC
