### ISSUE TITLE
Neogeo CD Subsystem Doesn't Support CHD File 

### ISSUE THREAD

**Issue by yudhiyou** [libretro/FBNeo#970] opened 2022-01-25 23:48 UTC
Current neogeo cd subsystem on fba neo doesn't support chd file. It only supports cue file. 
Can you add support for chd file? Because chd format is very helpful for reducing disk space. 

Thank you...

**Comment by barbudreadmon** [comment] 2022-01-26 08:23
duplicate of https://github.com/libretro/FBNeo/issues/11

**Closed by barbudreadmon** 2022-01-26 08:23 UTC
