### ISSUE TITLE
Disappear "the custom assemby keys" in some game's core options

### ISSUE THREAD

**Issue by leoxxx** [libretro/FBNeo#226] opened 2020-01-14 11:06 UTC
"The custom assemby keys" in some game's(kov series) core options in FBAlpha.
Now disappear in FBNeo.
Maybe it can add in game input.

**Comment by barbudreadmon** [comment] 2020-01-14 11:51
duplicate of https://github.com/libretro/FBNeo/issues/194

**Closed by barbudreadmon** 2020-01-14 11:51 UTC
