### ISSUE TITLE
Flipped shader textures in vertical games

### ISSUE THREAD

**Issue by Starman99x** [libretro/FBNeo#1044] opened 2023-03-24 18:17 UTC
When loading some vertical aspect ratio games with FBNeo core, the texture image.png (bezel & overlay) of the applied shader might get flipped upside down, this problem does not occur with horizontal aspect games, nor does it occur with MAME core.

Here are some games affected by this bug:

- Circus Charlie (level select, set 1)
- Contra (US / Asia, set 1)
- Donkey Kong (US set 1)
- Donkey Kong Junior (US set F-2)
- Donkey Kong 3 (US)
- Detana!! Twin Bee (Japan ver. J)
- Final Star Force (USA)
- Galaga (Namco rev. B)
- Galaxian (Namco set 1)
- kiKi KaiKai
- Mappy (USA)
- MS Pacman
- Pac-Man (Midway)
- Pooyan

And these are some games that are NOT affected by this bug:

- 1941 - Counter Attack (900227 World)
- 1942 (Revision B)
- 1943: The Battle of Midway (Euro)
- 19XX - the war against destiny (960104 Euro)
- Ikari Warriors (US JAMMA)
- Punch-Out!! (Rev B)

My core settings are mostly default, my OS is Windows 7. And here's a [shader preset for testing](https://mega.nz/file/KGgzDDhS#ynxVUMzmKdhS99riwbB7aFNVxQmxU7OrTRWGlA9imfc), unpack the .slangp file to RetroArch/shaders, and move the .png file to: shaders_slang/bezel/koko-aio/textures.

Screenshot of a wrong flipped example:

![Screenshot_6](https://user-images.githubusercontent.com/69786862/227597985-5b2ab2cf-0668-4d2e-bfbf-f126f80dc911.png)

Screenshot of a correct example:
![Screenshot_7](https://user-images.githubusercontent.com/69786862/227598027-8e540a67-6fb9-4063-ac0f-ac655e15b25f.png)

**Comment by barbudreadmon** [comment] 2023-03-25 06:37
Duplicate of https://github.com/libretro/FBNeo/issues/1036.
MAME is the one being broken as explained in https://github.com/libretro/mame/issues/261
If you have doubts about this, you can easily confirm scanlines must be rotated by looking at footage of a real vertical game pcb : https://youtu.be/YAxjdD0fnfk?t=23
Closing.

**Comment by SamRetro** [comment] 2023-03-25 11:27
I'm not talking about scanlines I'm talking about the overlay.png used by the shader, notice in the screenshot how the flames are upside down in Donkey Kong:

![Picsart_23-03-25_13-23-55-097](https://user-images.githubusercontent.com/69786862/227714612-96716822-0794-4c34-a6ec-239b112d51f7.jpg)

Please read my issue again I've included a lot of details.

**Comment by barbudreadmon** [comment] 2023-03-25 14:29
Oh, i got misled because you said mame has the correct behavior, which is not the case as explained in https://github.com/libretro/mame/issues/261, sorry about that.

The answer remains the same though, FBNeo is sending the rotation through the libretro api, so that the frontend can decide how to handle that information.
That rotation can be 0/90/180/270 depending on the running game, meaning it can be rotated vertically in both directions, which i suppose explain why those overlay textures can go both direction. 

FBNeo is behaving as it should, the problem lies in how retroarch and that shader are handling this.

**Comment by SamRetro** [comment] 2023-03-25 14:32
But why this doesn't happen with all vertical games?
For example both Donkey Kong and 1943 are vertical games, yet Donkey Kong will flip the image, while 1943 will keep it as it should.

**Comment by barbudreadmon** [comment] 2023-03-25 14:37
>For example both Donkey Kong and 1943 are vertical games, yet Donkey Kong will flip the image, while 1943 will keep it as it should.

As i explained, some vertical games are rotated 90°, and some are rotated 270°, which *probably* explains that difference.

Additionally, the issue can probably be solved by having retroarch send the rotation index to the shader, so that the shader can account for whether the rotation is 90° or 270°.
It's possible in glsl (i sent a PR for this 2 years ago : https://github.com/libretro/RetroArch/pull/12827), but someone still needs to port it to slang

**Comment by SamRetro** [comment] 2023-03-25 15:16
Ok thank you, now I get it. If you could reach out to RA devs about it, would be great, since you know better than me about what should be done.

**Comment by barbudreadmon** [comment] 2023-03-25 15:25
I was briefly in contact with @HyperspaceMadness when i wrote https://github.com/libretro/RetroArch/pull/12827. I think he is the author of the "megabezel pack" if that's what you are using. I remember he mentioned being interested in porting https://github.com/libretro/RetroArch/pull/12827 to slang but i'm not sure it's still on his roadmap.

I'll re-open this issue for now, even if it's not exactly a FBNeo issue.

**Comment by barbudreadmon** [comment] 2023-03-26 18:33
I'd rather have the problem fixed than using some weird workaround core side.

https://github.com/libretro/RetroArch/pull/15136 will allow rotation awareness in any shader. 
As for whether this is merged and shaders properly use it, this is not my call.

**Comment by barbudreadmon** [comment] 2023-03-29 17:40
Feature merged into RA, i'll close.

**Closed by barbudreadmon** 2023-03-29 17:40 UTC
Labels: retroarch issue
