### ISSUE TITLE
Button Combinations for NeoGeo games

### ISSUE THREAD

**Issue by Kikasuru** [libretro/FBNeo#707] opened 2021-04-02 13:51 UTC
Hey, is there a way that you can add button combinations (like AB or BC ect.) when playing a NeoGeo game?  That'd be awesome, thank you!

**Comment by barbudreadmon** [comment] 2021-04-02 20:21
Duplicate of https://github.com/libretro/FBNeo/issues/509 and several other issues.
Will be available when RetroArch will provide support for this.

**Closed by barbudreadmon** 2021-04-02 20:21 UTC

**Comment by barbudreadmon** [comment] 2021-04-22 10:19
Some update about this : the most i would be able to map for neogeo games with current libretro limitation would be 4 macros (over the 11 possible combinations), if someone is willing to provide a list of the 4 most useful ones, i'll consider implementing them.
